### PR TITLE
Added New BPs

### PR DESCRIPTION
**Pull request by KhArtNJava**
Added BPs:

Index
Create Index
Create Indexes
Drop Index
Drop Table

### CODE REVIEW

**Comment by KhArtNJava** [comment]
I've changes old incorrect Author record of my prev commits. Changed by tutorial https://help.github.com/articles/changing-author-info/ and script:

```
git filter-branch --env-filter '

OLD_EMAIL="аыыа"
CORRECT_NAME="KhArtNJava"
CORRECT_EMAIL="khartnjava@gmail.com"

if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
```

**Comment by Jusas** [comment]
Tried this, it creates quite a messy history with double commit entries. I'd rather not do this (regarding editing of the author record).

**Comment by Jusas** [comment]
Well, looks kind of messy with the double commits but what can you do. Merged.

**Comment by KhArtNJava** [comment]
I am sorry for this... 
I rarely do PR for other projects, and for my projects I never observe settings of the author.

**Pull request merged**
