### PR TITLE
Added VS2013 project for SQLite and build fix.

### PR DESCRIPTION
**Pull request by KhArtNJava**
Added VS2013 project for SQLite and build fix.

### CODE REVIEW

**Comment by KhArtNJava** [comment]
Did you forgot about my PR? :)

**Comment by Jusas** [comment]
Hi, sorry for not responding earlier, I've been away on holiday.
The problem with this solution is that it's Windows specific. I'd prefer a multi-platform solution, a makefile for example. Right now you can only build for Windows which is something I'd like to see changed. The reason I only included Windows x86 and x64 binaries earlier was because I could only build for Windows myself as I do not have a Mac available. Optimally we'd have a build system in place that could build different binaries depending on your platform but in the meantime I feel we should just go with binaries instead of bringing extra luggage in the form of platform specific dependency projects.

**Comment by KhArtNJava** [comment]
Why you are not accept PR? There are some new BPs in my PR...

About your idea - it's possible to realize incrementally...

Can't understand why you are rejected my PR...

**Comment by Jusas** [comment]
Sorry for not being clear, I'd be happy to accept everything all commits except the SQLite Visual Studio project - that's simply because I'd like to keep this plugin fully multi-platform. A Mac user cannot use Visual Studio and therefore that solution is not ideal. I'm sure it's not a game breaker for you - I can probably come up with a suitable makefile that can be used in both Windows and Mac myself.

**Pull request closed without merging**
